### ISSUE TITLE
handle ip v6 -> ipv4 subnet syntax

### ISSUE THREAD

**Issue by frank-dspeed** [snd/url-pattern#46]
arg1 === '::ffff:127.0.0.1', parsed === undefined
```
/server/node_modules/url-pattern/lib/url-pattern.js:391
      throw new Error("couldn't parse pattern");
      ^

Error: couldn't parse pattern
    at new UrlPattern (/server/node_modules/url-pattern/lib/url-pattern.js:391:13)
    at exports.getService (/server/node_modules/@feathersjs/socket-commons/lib/utils.js:74:21)
    at _run (/server/node_modules/@feathersjs/socket-commons/lib/utils.js:98:32)
    at exports.runMethod (/server/node_modules/@feathersjs/socket-commons/lib/utils.js:123:3)
    at Socket.socket.on.args (/server/node_modules/@feathersjs/socket-commons/lib/index.js:25:11)
    at Socket.emit (events.js:164:20)
    at Socket.onevent (/server/node_modules/socketio-wildcard/index.js:14:17)
    at Socket.onpacket (/server/node_modules/socket.io/lib/socket.js:322:12)
    at /server/node_modules/socket.io/lib/client.js:197:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

```

**Comment by snd** [comment]
this is not a bug in url-pattern.

if a `:` (configurable through `options.segmentNameStartChar`, https://github.com/snd/url-pattern#customize-the-pattern-syntax) occurs in the pattern, then at least one char from `options.segmentNameCharset` must follow.

`::` causes a parse error since the first `:` is not followed by any char in `options.segmentNameCharset`.

**simply escaping every `:` that doesn't start a named segment by replacing it by `\\:` should resolve the issue.**

let me know if this solves the issue or if you have any further questions!

i'll keep this open since the error message could be improved.

**Comment by frank-dspeed** [comment]
@snd it looks solved thanks for pointing that out!
